- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-influxdb-helm-lint
        - nebulous-influxdb-build-container-images
        - nebulous-influxdb-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-influxdb-helm-lint
        - nebulous-influxdb-upload-container-images
        - nebulous-influxdb-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-influxdb-promote-container-images
