apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulous-influxdb.fullname" . }}-secrets
  labels:
    {{- include "nebulous-influxdb.labels" . | nindent 4 }}
type: Opaque
data:
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ .Values.secrets.DOCKER_INFLUXDB_INIT_PASSWORD | b64enc | quote }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.secrets.DOCKER_INFLUXDB_INIT_ADMIN_TOKEN | b64enc | quote }}